name: Gitconvex React UI pipeline

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install tailwindcss
      - run: npm i -g create-react-app tailwindcss@1.6.0
      - run: npm run build:tailwind
      - run: npm test && npm run build
      - name: Droplet commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            /opt/workroom/gitconvex-deploy.sh gitconvex-ui
