name: Gitconvex build deploy

on:
  push:
    branches: [ v2.0.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          
      - name: Run test cases
        run: |
          export GOTESTENV=ci && go test -v ./...
      
      - name: Run sample build
        run: |
          go build -v

      # Initiating build and S# deployment 
      - name: Starting S3 deployment script from droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_PRIVATE_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            /opt/workroom/aws-build/init-deploy.sh
            /opt/workroom/aws-build/windows-deploy.sh
            /opt/workroom/aws-build/linux-deploy.sh
            /opt/workroom/aws-build/macos-deploy.sh
